---
version: '3'
services:
  mongodb:
    image: mongo:3.4.24-xenial
    volumes:
      - ./storage/mongodb:/data/db:z
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - ./storage/redis:/data:z
    restart: always

  hpfeeds3:
    image: stingar/hpfeeds3:1.9.1
    links:
      - mongodb:mongodb
    ports:
      - "10000:10000"
    restart: always

  mnemosyne:
    image: stingar/mnemosyne:1.9.1
    env_file:
      - ./config/sysconfig/mnemosyne.env
    links:
      - mongodb:mongodb
      - hpfeeds3:hpfeeds3
    restart: always

  chnserver:
    image: stingar/chn-server:1.9.1
    volumes:
      - ./storage/chnserver/sqlite:/opt/sqlite:z
      - ./certs:/etc/letsencrypt:z
    env_file:
      - ./config/sysconfig/chnserver.env
    links:
      - mongodb:mongodb
    ports:
      - "80:80"
      - "443:443"
    restart: always
  cowrie:
    build: honeypot
    restart: always
    volumes:
      - configs:/etc/cowrie
      - ./honeypot/conf/:/code/d4-core/client/conf/
      - ./honeypot/entrypoint.sh:/code/entrypoint.sh
    ports:
      - "2222:2222"
      - "23:2223"
    env_file:
      - honeypot/cowrie.env
      - honeypot/d4-client.env
    depends_on:
      - chnserver
volumes:
    configs:
